package repl.simple.mathematica.Actions;

import com.intellij.openapi.actionSystem.AnActionEvent;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.ui.DialogWrapper;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import org.jetbrains.annotations.Nullable;
import repl.simple.mathematica.MathREPLBundle;

import javax.swing.*;
import java.awt.*;
import java.util.ResourceBundle;

/**
 * This action shows the information form about the plugin
 */
public class AboutAction extends MathREPLBaseAction {
    /**
     * Class constructor binds
     */
    public class MyAboutDialog extends DialogWrapper {
        private JPanel myPanel;
        private JTextArea myAboutInfo;
        private Project myProject;

        MyAboutDialog(Project project) {
            super(project, true);
            myAboutInfo.setText(MathREPLBundle.message("aboutInfo"));
            myProject = project;
            init();
            this.pack();
        }

        @Nullable
        @Override
        protected JComponent createCenterPanel() {
            return myPanel;
        }

        {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
            $$$setupUI$$$();
        }

        /**
         * Method generated by IntelliJ IDEA GUI Designer
         * >>> IMPORTANT!! <<<
         * DO NOT edit this method OR call it in your code!
         *
         * @noinspection ALL
         */
        private void $$$setupUI$$$() {
            myPanel = new JPanel();
            myPanel.setLayout(new GridLayoutManager(2, 2, new Insets(5, 5, 5, 5), -1, -1));
            myAboutInfo = new JTextArea();
            myAboutInfo.setColumns(80);
            myAboutInfo.setEditable(false);
            myAboutInfo.setLineWrap(true);
            myAboutInfo.setText("Label");
            myAboutInfo.setWrapStyleWord(true);
            myPanel.add(myAboutInfo, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(500, 100), null, 0, false));
            final Spacer spacer1 = new Spacer();
            myPanel.add(spacer1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        }

        /**
         * @noinspection ALL
         */
        public JComponent $$$getRootComponent$$$() {
            return myPanel;
        }
    }

    ;

    /**
     * Shows the information dialog with plugin info
     * @param anActionEvent
     */
    @Override
    public void actionPerformed(final AnActionEvent anActionEvent) {
        new MyAboutDialog(anActionEvent.getProject()).show();
    }
}
